### ISSUE TITLE
Compile project with Gemfile and/or gemspec

### ISSUE THREAD

**Issue by mamantoha** [pmq20/ruby-compiler#7]
Hi.
First of all, I would like to thank you for the great project.

I use latest `ruby-compiler` from the GitHub.

When I try to compile a project with `Gemfile` and `gemspec` I get an error:

```
Cannot find entrance /Users/user/ruby/crowdin-cli/bin/crowdin-cli, available entrances are bundle, bundler, crowdin-cli.
```

I look through the code. And it seems like it tries to get the absolute path to the binary.

**Comment by pmq20** [comment]
Have you tried use the entrance string `crowdin-cli` instead of the whole path?

**Comment by mamantoha** [comment]
Yup

```
crowdin-cli(master ✗) ruby ../ruby-compiler/bin/rubyc crowdin-cli

[...]

Cannot find entrance /Users/user/ruby/crowdin-cli/crowdin-cli, available entrances are bundle, bundler, crowdin-cli.
```

**Comment by pmq20** [comment]
Thanks for reporting. Indeed a bug. Let me fix it ASAP.

**Comment by pmq20** [comment]
@mamantoha Fixed in c9cb1a0, works on my local machine:

![image](https://user-images.githubusercontent.com/13315/28401171-c038df72-6d4a-11e7-909b-8bca5f14f449.png),

**Comment by mamantoha** [comment]
Thank! It's almost working.

https://github.com/pmq20/ruby-compiler/commit/c9cb1a0df7bd18302c44e1eca2d3ded4998517d3#commitcomment-23200482

**Comment by mamantoha** [comment]
@pmq20 I have a question that does not relate to this issue.
Why do you use `utf-8` with `dos` line endings and not `unix` for files?

**Comment by pmq20** [comment]
@mamantoha Sorry I did not pay attention. Does this matter to any issues?
